# Generated by Django 2.0.3 on 2018-03-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fact Title')),
            ],
        ),
        migrations.AddField(
            model_name='fact',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menace.FactTitle', verbose_name='Title'),
        ),
    ]
